579c48e211ae952530ffc8738709f078d5dd215e:
  name: Mario Kart 64 [US]
  path: yamls/us
  config:
    gbi: F3DEX_MK64
    sort: OFFSET
    enums: 
      - include/defines.h
    output:
      binary: mk64.o2r
      headers: include/assets
      code: assets/code
  segments:
    - 0x000000 # 0x00
    - 0x000000 # 0x01
    - 0x12AAE0 # 0x02
    - 0x000000 # 0x03
    - 0x000000 # 0x04
    - 0x000000 # 0x05
    - 0x825800 # 0x06
    - 0x000000 # 0x07
    - 0x000000 # 0x08
    - 0x88CD70 # 0x09
    - 0x729A30 # 0x0A
    - 0x821D10 # 0x0B
    - 0x7FA3C0 # 0x0C
    - 0x132B50 # 0x0D
    - 0x000000 # 0x0E
    - 0x145470 # 0x0F
